stream node changes to db
robusta-dev/robusta pull request #1008
Opened 2023-07-26 08:25 UTC by RoiGlinik

2023-08-08 08:46 UTC, ganeshrvel requested changes
Good work. Left some comments.

2023-08-08 08:46 UTC, ganeshrvel commented on src/robusta/core/discovery/discovery.py
> +    def create_service_info(obj: Union[Deployment, DaemonSet, StatefulSet, Pod, ReplicaSet]) -> ServiceInfo:
any particular reason we need this wrapper method? cant we just use the exisiting `__create_service_info`?

2023-08-08 12:16 UTC, RoiGlinik commented on playbooks/robusta_playbooks/event_enrichments.py
> +    elif isinstance(new_resource, Pod) and (new_resource.metadata.owner_references or is_pod_finished(new_resource)):
yea you are right, ill update it

2023-08-10 09:14 UTC, ganeshrvel approved these changes

2023-08-10 09:15 UTC, merged

2023-08-13 10:47 UTC, RoiGlinik commented on src/robusta/core/sinks/robusta/robusta_sink.py
> +
check if equal and pass