renamed, and updated docs
robusta-dev/robusta pull request #295
Opened 2022-04-20 07:46 UTC by Avi-Robusta

2022-04-20 15:52 UTC, aantn commented on playbooks/robusta_playbooks/pod_troubleshooting.py
> +    Prompts the user with debugging options for all python processes currently running in the pod.
Excellent

2022-04-20 15:56 UTC, aantn commented
@Avi-Robusta looks good.

Can you also add a screenshot for each playbook to `playbooks/robusta_playbooks/images`? 

The image will automatically be added to the docs if it has the same name as the playbook function.

2022-04-20 15:56 UTC, aantn requested changes
Please add the images. Other than that looks good.

2022-04-21 08:30 UTC, aantn commented
@Avi-Robusta hmm, sorry to nitpick but after looking at the images I'm slightly confused. Does `python_process_inspector` let you choose between the different debugging options (like we do in `java_process_inspector`) or is it just a wrapper for the stack trace playbook which asks you to choose a process first?

I'd like to keep it as consistent as possible with the other one to avoid confusion.

2022-04-24 08:53 UTC, Avi-Robusta commented
currently it is just stack trace but it used to have memory too, i think it was removed because it was determined to be less useful but it can be added again

2022-09-20 06:48 UTC, closed without merging