Added the support for Query string in the Prometheus_url field
robusta-dev/robusta pull request #922
Opened 2023-06-02 13:54 UTC by ganeshrvel

2023-06-03 12:28 UTC, sumeet-zuora commented
Do we know when this would be released

2023-06-09 21:02 UTC, sumeet-zuora commented
This PR would really help our team to adopt Robusta, can we get some traction on this.. not sure what is the priority on this

2023-06-11 11:36 UTC, pablos44 requested changes
Hey, it is much simpler and more flexible to have a separate parameter for query params than gluing them to `prometheus_url`. let's add `prometheus_url_query`  param for this purpose.

2023-06-27 09:13 UTC, pablos44 commented on src/robusta/utils/common.py
> +    return {key: value[0] for key, value in query_params.items()}
It can happen that there is the same key repeated a few times in a query. So value[0] is not always sufficient

2023-06-27 14:31 UTC, pablos44 approved these changes

2023-06-28 07:48 UTC, merged